---
name: Checks
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Test
        run: |
          pipenv run python -m unittest test_board
          pipenv run python -m unittest test_player
          pipenv run python -m unittest test_damage_falling_items
          pipenv run python -m unittest test_error_item
          pipenv run python -m unittest test_warning_item
          pipenv run python -m unittest test_bug_item
          pipenv run python -m unittest test_tick_item
          pipenv run python -m unittest test_python_item
          pipenv run python -m unittest test_duck_item
